name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0



      # TODO build, publish to docker hub, deploy to k8s
      - name: UnitTests
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: |
          docker compose up postgres -d
          pip install -r requirements.txt
          export DATABASE_URL="postgresql://program:test@localhost:5432/flights"
          pytest app/FlightService/tests.py
          export DATABASE_URL="postgresql://program:test@localhost:5432/tickets"
          pytest app/TicketService/tests.py
          export DATABASE_URL="postgresql://program:test@localhost:5432/privileges"
          pytest app/BonusService/tests.py
          docker compose down

      - uses: docker/setup-buildx-action@v2 
      - name: Build images
        timeout-minutes: 10
        run: docker compose build
      
      - name: Publishing
        timeout-minutes: 10
        run: |
          docker login -u shadowxtof -p ${{secrets.DOCKERHUB_PASSWORD}}
          docker tag bmstu-semester_9-rsoi-lab4-flights shadowxtof/bmstu-semester_9-rsoi-lab4-flights
          docker push shadowxtof/bmstu-semester_9-rsoi-lab4-flights
          docker tag bmstu-semester_9-rsoi-lab4-bonuses shadowxtof/bmstu-semester_9-rsoi-lab4-bonuses
          docker push shadowxtof/bmstu-semester_9-rsoi-lab4-bonuses
          docker tag bmstu-semester_9-rsoi-lab4-tickets shadowxtof/bmstu-semester_9-rsoi-lab4-tickets
          docker push shadowxtof/bmstu-semester_9-rsoi-lab4-tickets
          docker tag bmstu-semester_9-rsoi-lab4-gateway shadowxtof/bmstu-semester_9-rsoi-lab4-gateway
          docker push shadowxtof/bmstu-semester_9-rsoi-lab4-gateway

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
      
      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v