name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0



      # TODO build, publish to docker hub, deploy to k8s
      
      
      - name: Set up k8s
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.16.4'

      - name: Publishing
        timeout-minutes: 10
        run: |
          touch ~/.kube/config
          echo "${KUBE_CONFIG}" | base64 -d > ~/.kube/config
          helm uninstall flights
          helm install flights ./ticketbuy -f ./ticketbuy/values-flights.yaml
          helm uninstall bonuses
          helm install bonuses ./ticketbuy -f ./ticketbuy/values-bonuses.yaml
          helm uninstall tickets
          helm install tickets ./ticketbuy -f ./ticketbuy/values-tickets.yaml
          helm uninstall gateway
          helm install gateway ./ticketbuy -f ./ticketbuy/values-gateway.yaml

          echo "84.201.149.237 ticketbuy.ru" >> /etc/hosts

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
      
      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v