name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0



      # TODO build, publish to docker hub, deploy to k8s
      
      
      - name: Publishing
        timeout-minutes: 10
        run: |
          
          curl -LO https://dl.k8s.io/release/`curl -LS https://dl.k8s.io/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl config use-context default --kubeconfig=test.kubeconfig
          kubectl get services
          
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm

          helm uninstall flights
          helm install flights ./ticketbuy -f ./ticketbuy/values-flights.yaml
          helm uninstall bonuses
          helm install bonuses ./ticketbuy -f ./ticketbuy/values-bonuses.yaml
          helm uninstall tickets
          helm install tickets ./ticketbuy -f ./ticketbuy/values-tickets.yaml
          helm uninstall gateway
          helm install gateway ./ticketbuy -f ./ticketbuy/values-gateway.yaml

          echo "84.201.149.237 ticketbuy.ru" >> /etc/hosts

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
      
      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v